### PR TITLE
Add DirectoryParser program

### PR DESCRIPTION
**Pull request by dbrgn**
The task parses every endpoint in the directory.

### CODE REVIEW

**Comment by dbrgn** [comment]
I changed it from a gradle task to a regular command line program, due to build system dependency woes.

Of all the endpoints that could be fetched without an error, the following could not be parsed:

Invalid open/close icon URLs:

- Eigenbaukombinat Halle FAILED: no protocol:

Invalid Facebook URL:

- Hackerspace KRK FAILED: no protocol: HackerspaceKrakow
- Hackerspace.gr FAILED: no protocol: hackerspacegr
- Nottinghack FAILED: no protocol: nottinghack
- Warsaw Hackerspace FAILED: no protocol: hackerspacepl
- Hacklabor FAILED: no protocol: hacklabor

Missing required fields:

- Makers Local 256 FAILED: Field 'location' is required, but it was missing
- Hackerspace Bremen e.V. FAILED: Field 'location' is required, but it was missing
- Apollo-NG FAILED: Field 'location' is required, but it was missing
- MidsouthMakers FAILED: Field 'issue_report_channels' is required, but it was missing
- HeatSync Labs FAILED: Field 'location' is required, but it was missing
- base48 FAILED: Field 'location' is required, but it was missing
- Sudo Room FAILED: Field 'location' is required, but it was missing
- Chaos Darmstadt FAILED: Field 'location' is required, but it was missing
- Maschinenraum FAILED: Field 'location' is required, but it was missing
- Garoa Hacker Clube FAILED: Field 'location' is required, but it was missing

Using "null" values where not allowed:

- Brixel FAILED: Unexpected JSON token at offset 22: Expected string literal but 'null' literal was found.
  - The `space` and `projects` fields are set to null

Stringified data type:

- Krautspace FAILED: Unexpected JSON token at offset 342: Expected start of the unquoted boolean literal.
  - The `state.open` field is a string (`"false"` instead of `false`)

Broken endpoint:

- nbsp FAILED: Unexpected JSON token at offset 0: Expected '{, kind: CLASS'
  - Temporary redirect to "space is closed" HTML page that breaks SpaceAPI. Corona?
- Chaosdorf FAILED: Unexpected JSON token at offset 0: Expected '{, kind: CLASS'
  - Empty response

Not yet analyzed (TODO):

- nordlab e. V. FAILED: Unexpected JSON token at offset 0: Expected '{, kind: CLASS'
    JSON input:
- Recompile FAILED: Unexpected JSON token at offset 0: Expected '{, kind: CLASS'
    JSON input:

**Comment by dbrgn** [comment]
For the issues above, I'd handle them as follows:

- Invalid open/close icon URLs: Invalid, should be fixed
- Invalid Facebook URL: Since this is quite a common error, we should probably just treat this as a string
- API v0.12: Cannot be supported easily together with v14 in a backwards compatible way. We should try to get them to switch.
- Missing required fields: Invalid, should be fixed
- Using "null" values where not allowed: Invalid, should be fixed
- Stringified data type: Invalid, should be fixed
- Broken endpoint: Invalid, should be fixed

@gidsi you've dealt a lot with validation. What are your thoughts on this?

(Since this is purely a parsing library and not a validation library, we can be a bit lenient on the parsing side, but in general I'd rather contact the space and ask them to fix the endpoint than to add hacks to the parser.)

**Comment by gidsi** [comment]
> @gidsi you've dealt a lot with validation. What are your thoughts on this?
> 
> (Since this is purely a parsing library and not a validation library, we can be a bit lenient on the parsing side, but in general I'd rather contact the space and ask them to fix the endpoint than to add hacks to the parser.)

It seem like you already fixed a fair amount of errors. What would you do with the invalid ones, drop them?

**Comment by dbrgn** [comment]
> What would you do with the invalid ones, drop them?

In the case of the parser, it would throw an exception when parsing.

Applied to the MyHackerspace app: These spaces could not be viewed, that's all.

**Comment by dbrgn** [comment]
I contacted MidsouthMakers (IRC), Brixel (Email), Krautspace (Email) and Chaosdorf (IRC) about the issues with their endpoints.

**Comment by gidsi** [comment]
> I contacted MidsouthMakers (IRC), Brixel (Email), Krautspace (Email) and Chaosdorf (IRC) about the issues with their endpoints.

Chaosdorf just moved the space and is a bit busy, thats my homebase :)

**Comment by dbrgn** [comment]
> Chaosdorf just moved the space and is a bit busy, thats my homebase :)

Yeah, I got it sorted out in IRC, they fixed it and also made it v14-compatible :tada: 

Brixel is also fixed.

**Pull request merged**
